constraint tree = [Sub, Mul, Val, Sub, Val, Val, Add, Val, Add, Val, Val];
constraint left = [2, 3, 0, 5, 0, 0, 8, 0, 10, 0, 0];
constraint right = [7, 4, 0, 6, 0, 0, 9, 0, 11, 0, 0];
constraint lowest = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
constraint highest = [11, 6, 3, 6, 5, 6, 11, 8, 11, 10, 11];
constraint indexes = [0, 0, 1, 0, 3, 4, 0, 5, 0, 2, 6];
constraint used = 6;
constraint tree_vals = [989, 1100, 25, 44, 50, 6, 111, 8, 103, 100, 3];
